=== janjirousekk/app/jirousek_jan.xsd
<!-- Odkaz na github: https://github.com/janjirousekk/app -->

<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    
    <xs:element name="app"> <!-- Koøenový element --> 
        <xs:complexType>
            <xs:sequence>
                <xs:element name="user" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:complexType name="user"> <!-- Obal pro uživatele --> 
        <xs:sequence>
            <xs:element ref="account" minOccurs="1" maxOccurs="1"/>
            <xs:element ref="config" minOccurs="1" maxOccurs="1"/>
            <xs:element ref="progress" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string" />
    </xs:complexType>
    
    <xs:element name="account"> <!-- Obal pro personální informace --> 
        <xs:complexType>
            <xs:sequence>
                <xs:element name="nick" type="xs:string"/>
                <xs:element name="email" type="xs:string"/>
                <xs:element name="password">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute type="xs:string" name="type"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="created" type="xs:date" />
                <xs:element name="last_login" type="xs:string" />
                <xs:element name="premium">
                    <xs:complexType>
                        <xs:attribute name="active" type="xs:boolean"></xs:attribute>
                    </xs:complexType>
                </xs:element>
                <xs:element name="premium_fromDate" type="xs:string" />
                <xs:element name="premium_toDate" type="xs:string" />
                <xs:element name="friends">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="friend" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute type="xs:string" name="id"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>    
    </xs:element>
    
    <xs:element name="config"> <!-- Grafické nastavení aplikace --> 
        <xs:complexType>
            <xs:sequence>
                <xs:element name="predefined" type="xs:string"/>
                <xs:element name="resolution" type="xs:string"/>
                <xs:element name="directx" type="xs:string"/>
                <xs:element name="vsync">
                    <xs:complexType>
                        <xs:attribute name="enable" type="xs:boolean"></xs:attribute>
                    </xs:complexType>
                </xs:element>
                <xs:element name="low_pc">
                    <xs:complexType>
                        <xs:attribute name="enable" type="xs:boolean"></xs:attribute>
                    </xs:complexType>
                </xs:element>
                <xs:element name="antialiasing" type="xs:string"/>
                <xs:element name="texture_quality" type="xs:string"/>
                <xs:element name="texture_filtering" type="xs:string"/>
                <xs:element name="light_guality" type="xs:string"/>
                <xs:element name="liquid" type="xs:string"/>
                <xs:element name="depth_of_field" type="xs:string"/>
                <xs:element name="shadows" type="xs:string"/>
                <xs:element name="range_render" type="xs:string"/>
                <xs:element name="range_shadows" type="xs:string"/>
                <xs:element name="range_objects" type="xs:string"/>
                <xs:element name="bloom" type="xs:integer"/>
                <xs:element name="motion_blur" type="xs:string"/>
                <xs:element name="fps">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute type="xs:integer" name="max_fps"/>
                                <xs:attribute type="xs:integer" name="max_bg_fps"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="new_models">
                    <xs:complexType>
                        <xs:attribute name="allow" type="xs:boolean"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="key_binding"> <!-- Natavení kláves --> 
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="key" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute type="xs:string" name="value"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType> 
    </xs:element>
    
    <xs:element name="progress"> <!-- Obal pro seznam postav uživatele --> 
        <xs:complexType>
            <xs:sequence>
                <xs:element name="character" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:string" name="name"/>
                            <xs:element type="xs:string" name="server"/>
                            <xs:element type="xs:string" name="realm"/>
                            <xs:element type="xs:integer" name="level"/>
                            <xs:element type="xs:string" name="race"/>
                            <xs:element type="xs:string" name="class"/>
                            <xs:element type="xs:string" name="specialization"/>
                            <xs:element type="xs:integer" name="item_lvl"/>
                            <xs:element type="xs:integer" name="rank_realm_pvp"/>
                            <xs:element type="xs:integer" name="rank_realm_pve"/>
                            <xs:element type="xs:integer" name="rank_global_pvp"/>
                            <xs:element type="xs:integer" name="rank_global_pve"/>
                            <xs:element name="location">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute type="xs:byte" name="posX"/>
                                            <xs:attribute type="xs:byte" name="posY"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
  </xs:element>

</xs:schema>

=== janjirousekk/app/jirousek_jan.xml
<!-- Odkaz na github: https://github.com/janjirousekk/app -->

<?xml version="1.0" encoding="UTF-8"?>
<app xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="jirousek_jan.xsd">
    <user id="a1">
        <account>
            <nick>regro</nick>
            <email>janjirousekk@gmail.com</email>
            <password type="MD5">955db0b81ef1989b4a4dfeae8061a9a6</password>
            <created>2017-02-05</created>
            <last_login>2017-04-19</last_login>
            <premium active="true"/>
            <premium_fromDate>2017-05-05</premium_fromDate>
            <premium_toDate>2018-01-01</premium_toDate>
            <friends>
                <friend id="a2"/>
                <friend id="a3"/>
            </friends>
        </account>
        <config>
            <predefined>custom</predefined>
            <resolution>1920x1080</resolution>
            <directx>11</directx>
            <vsync enable="true"/>
            <low_pc enable="false"/>
            <antialiasing>ssao</antialiasing>
            <texture_quality>ultra</texture_quality>
            <texture_filtering>ultra</texture_filtering>    
            <light_guality>ultra</light_guality>
            <liquid>high</liquid>
            <depth_of_field>disable</depth_of_field>
            <shadows>high</shadows>
            <range_render>normal</range_render>
            <range_shadows>normal</range_shadows>
            <range_objects>normal</range_objects>
            <bloom>4</bloom>
            <motion_blur>0</motion_blur>
            <fps max_fps="60" max_bg_fps="30"/>
            <new_models allow="true" />
            <key_binding>
                <key value="W">+forward</key>
                <key value="S">+back</key>
                <key value="A">+left</key>
                <key value="D">+right</key>
                <key value="1">+fire1</key>
                <key value="2">+fire2</key>
                <key value="3">+fire3</key>
                <key value="4">+fire4</key>
            </key_binding>
        </config>
        <progress>
            <character>
                <name>norbit</name>
                <server>EU01</server>
                <realm>czech</realm>
                <level>110</level>
                <race>orc</race>
                <class>warrior</class>
                <specialization>protection</specialization>
                <item_lvl>940</item_lvl>
                <rank_realm_pvp>1</rank_realm_pvp>
                <rank_realm_pve>1</rank_realm_pve>
                <rank_global_pvp>1</rank_global_pvp>
                <rank_global_pve>1</rank_global_pve>
                <location posX="50" posY="50"/>
            </character>
        </progress>
    </user>
    <user id="a2">
        <account>
            <nick>dxf</nick>
            <email>nejakyemail@gmail.com</email>
            <password type="MD5">355db32wwf198ee4a4dfeae8ab1a9a6</password>
            <created>2017-04-02</created>
            <last_login>2017-04-19</last_login>
            <premium active="false"/>
            <premium_fromDate>0000-00-00</premium_fromDate>
            <premium_toDate>0000-00-00</premium_toDate>
            <friends>
                <friend id="a1"/>
            </friends>
        </account>
        <config>
            <predefined>custom</predefined>
            <resolution>1024x768</resolution>
            <directx>9</directx>
            <vsync enable="false"/>
            <low_pc enable="true"/>
            <antialiasing>disable</antialiasing>
            <texture_quality>low</texture_quality>
            <texture_filtering>low</texture_filtering>    
            <light_guality>disable</light_guality>
            <liquid>low</liquid>
            <depth_of_field>disable</depth_of_field>
            <shadows>disable</shadows>
            <range_render>low</range_render>
            <range_shadows>low</range_shadows>
            <range_objects>fair</range_objects>
            <bloom>0</bloom>
            <motion_blur>0</motion_blur>
            <fps max_fps="60" max_bg_fps="30"/>
            <new_models allow="false" />
            <key_binding>
                <key value="W">+forward</key>
                <key value="S">+back</key>
                <key value="A">+left</key>
                <key value="D">+right</key>
                <key value="1">+fire2</key>
                <key value="2">+fire3</key>
                <key value="3">+fire1</key>
                <key value="4">+fire4</key>
            </key_binding>
        </config>
        <progress>
            <character>
                <name>klaves</name>
                <server>US02</server>
                <realm>canada</realm>
                <level>98</level>
                <race>elf</race>
                <class>hunter</class>
                <specialization>beastmaster</specialization>
                <item_lvl>720</item_lvl>
                <rank_realm_pvp>3500</rank_realm_pvp>
                <rank_realm_pve>2151</rank_realm_pve>
                <rank_global_pvp>2800</rank_global_pvp>
                <rank_global_pve>3600</rank_global_pve>
                <location posX="40" posY="20"/>
            </character>
        </progress>
    </user>
    <user id="b34">
        <account>
            <nick>grazlik</nick>
            <email>grazlik@email.cz</email>
            <password type="MD5">3256cadc51d024e6529f756ec60a5e86</password>
            <created>2014-03-08</created>
            <last_login>2016-04-19</last_login>
            <premium active="false"/>
            <premium_fromDate>0000-00-00</premium_fromDate>
            <premium_toDate>0000-00-00</premium_toDate>
            <friends>
                <friend id="a2"/>
            </friends>
        </account>
        <config>
            <predefined>custom</predefined>
            <resolution>1920x1080</resolution>
            <directx>11</directx>
            <vsync enable="true"/>
            <low_pc enable="false"/>
            <antialiasing>msao</antialiasing>
            <texture_quality>high</texture_quality>
            <texture_filtering>high</texture_filtering>    
            <light_guality>high</light_guality>
            <liquid>normal</liquid>
            <depth_of_field>low</depth_of_field>
            <shadows>high</shadows>
            <range_render>normal</range_render>
            <range_shadows>normal</range_shadows>
            <range_objects>normal</range_objects>
            <bloom>4</bloom>
            <motion_blur>0</motion_blur>
            <fps max_fps="60" max_bg_fps="30"/>
            <new_models allow="true" />
            <key_binding>
                <key value="W">+forward</key>
                <key value="S">+back</key>
                <key value="A">+left</key>
                <key value="D">+right</key>
                <key value="1">+fire1</key>
                <key value="2">+fire2</key>
                <key value="3">+fire3</key>
                <key value="4">+fire4</key>
            </key_binding>
        </config>
        <progress>
            <character>
                <name>jezek</name>
                <server>EU01</server>
                <realm>czech</realm>
                <level>40</level>
                <race>human</race>
                <class>paladin</class>
                <specialization>holy</specialization>
                <item_lvl>76</item_lvl>
                <rank_realm_pvp>45</rank_realm_pvp>
                <rank_realm_pve>65</rank_realm_pve>
                <rank_global_pvp>1200</rank_global_pvp>
                <rank_global_pve>1400</rank_global_pve>
                <location posX="120" posY="10"/>
            </character>
            <character>
                <name>norbitek</name>
                <server>EU01</server>
                <realm>czech</realm>
                <level>110</level>
                <race>undead</race>
                <class>warlock</class>
                <specialization>destruction</specialization>
                <item_lvl>940</item_lvl>
                <rank_realm_pvp>5</rank_realm_pvp>
                <rank_realm_pve>5</rank_realm_pve>
                <rank_global_pvp>5</rank_global_pvp>
                <rank_global_pve>5</rank_global_pve>
                <location posX="30" posY="30"/>
            </character>
        </progress>
    </user>
    <user id="c34">
        <account>
            <nick>hohoho</nick>
            <email>hohoho@gmail.com</email>
            <password type="MD5">8b0dc2e34844337434b8475108a490ab</password>
            <created>2016-05-05</created>
            <last_login>2017-04-15</last_login>
            <premium active="true"/>
            <premium_fromDate>2016-05-05</premium_fromDate>
            <premium_toDate>2017-01-01</premium_toDate>
            <friends>
                <friend id="a1"/>
                <friend id="b34"/>
            </friends>
        </account>
        <config>
            <predefined>custom</predefined>
            <resolution>1280x720</resolution>
            <directx>9</directx>
            <vsync enable="false"/>
            <low_pc enable="false"/>
            <antialiasing>disable</antialiasing>
            <texture_quality>normal</texture_quality>
            <texture_filtering>normal</texture_filtering>    
            <light_guality>disable</light_guality>
            <liquid>low</liquid>
            <depth_of_field>normal</depth_of_field>
            <shadows>normal</shadows>
            <range_render>normal</range_render>
            <range_shadows>normal</range_shadows>
            <range_objects>high</range_objects>
            <bloom>3</bloom>
            <motion_blur>0</motion_blur>
            <fps max_fps="30" max_bg_fps="30"/>
            <new_models allow="false" />
            <key_binding>
                <key value="W">+forward</key>
                <key value="S">+back</key>
                <key value="A">+left</key>
                <key value="D">+right</key>
